server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: borrowing-service
          uri: lb://BORROWING-SERVICE
          predicates:
            - Path=/api/borrowings/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
